config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  resources :events do
    member do
      patch 'assign_user_to'
      patch 'delete_user_from'
    end
  end

  resources :users do
    member do
      patch 'make_admin'
    end
  end

  get   '/signup',  to: 'users#new'
  post  '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :users, autosave: true

  validates :name, presence: true
  validates :location, presence: true
  validates :start, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events
  has_and_belongs_to_many :events, autosave: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  attr_accessor :remember_token

  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :surname, presence: true, length: { maximum: 75 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  class << self
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_admin_user,  only: [:new, :create, :edit, :update]

  def new
    @event = Event.new
  end

  def index
    @events = Event.where('start >= ?', Date.today).order(:start)
                  .paginate(page: params[:page], per_page: 10)
  end

  def show
    @event = Event.find(params[:id])
    @users = @event.users.order(:name).paginate(page: params[:page], per_page: 10)
  end

  def create
    @event = Event.new(event_params)
    @user = @event.build_user(id: session[:user_id])
    if @event.save
      flash[:success] = "Event created"
      redirect_to edit_user_path(current_user)
    else
      render 'new'
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      flash[:success] = "Event updated"
      redirect_to event_path(@event)
    else
      render 'edit'
    end
  end

  def assign_user_to
    @event = Event.find(params[:id])
    @event.users << current_user unless @event.users.include?(current_user)
    redirect_to event_path(@event)
  end

  def delete_user_from
    @event = Event.find(params[:id])
    @event.users.delete(current_user) if @event.users.include?(current_user)
    redirect_to event_path(@event)
  end

  private

    def event_params
      params.require(:event).permit(:name, :location,
                                    :start, :end, :link)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login,  only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or edit_user_path(user)
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user,        only: [:edit, :update]
  before_action :require_admin_user,  only: [:new, :create, :destroy, :make_admin]

  def new
    @user = User.new
  end

  def index
    @users = User.order(:surname).paginate(page: params[:page], per_page: 20)
  end

  def show
    @user = User.find(params[:id])
    @events = @user.events.order(:start).paginate(page: params[:page], per_page: 10)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "New user created"
      redirect_to edit_user_path(@user)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def make_admin
    @user = User.find(params[:id])
    if @user.update_attribute(:admin, 1)
      flash[:success] = @user.name + " " + @user.surname + " has got admin privileges now"
    else
      flash[:danger] = @user.name + " " + @user.surname + " already is an admin"
    end
    redirect_to user_path(@user)
  end

  private

    def user_params
      params.require(:user).permit(:name, :surname, :email, :sex,
                                   :password, :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to root_url unless current_user?(@user) || current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  $global_counter = 0;

  def global_counter_assign(counter)
    $global_counter = counter >= 0 ? counter : 0;
  end

  def global_counter_add
    $global_counter += 1
  end

  def full_title(page_title = '')
    base_title = "Husaria Race Team"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user?(user)
    user == current_user
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default)
    redirect_to session[:forwarding_url] || default
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

  ########### Before actions ################

  def require_login
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  def require_admin_user
    unless current_user.admin?
      flash[:danger] = "You have to log in as admin."
      redirect_to root_url
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_error_messages.html.erb
<% if @event.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@event.errors.count, "error") %>.
    </div>
    <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/events/_event.html.erb
<div class="col-md-6">
  <a href="<%= event_path(event) %>" class="event-jumbotron">
    <div class="jumbotron event-jumbotron">
      <p>Title: <%= event.name %></p>
      <p>Location: <%= event.location %></p>
      <p>Date: <%= event.start.strftime("%F at %k:%M") %>
    </div>
  </a>
</div>

app/views/events/_users.html.erb
<% @users.each do |user| %>
  <div class="col-sm-6 col-md-6">
    <a href="<%= user_path(user) %>" class="event-jumbotron">
      <div class="jumbotron event-jumbotron">
        <p><%= user.name + " " + user.surname %></p>
      </div>
    </a>
  </div>
<% end %>

app/views/events/edit.html.erb
<% provide(:title, "Edit event") %>
<h1>Edit event</h1>

<div class="container">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@event) do |f| %>
      <%= render 'error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :location %>
      <%= f.text_field :location, class: 'form-control' %>

      <%= f.label :start, "Start time"%>
      <div class="form-group">
        <div class="input-group date">
          <%= f.text_field :start, class: 'form-control', id: 'datetimepicker'%>
          <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
          </span>
        </div>
      </div>

      <%= f.label :end, "End time"%>
      <div class="form-group">
        <div class="input-group date">
          <%= f.text_field :end, class: 'form-control', id: 'datetimepicker2'%>
          <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
          </span>
        </div>
      </div>

      <%= f.label :link %>
      <%= f.text_field :link, class: 'form-control' %>

      <%= f.submit "Edit event", class: 'btn btn-danger' %>
    <% end %>
  </div>
</div>

app/views/events/index.html.erb
<% provide(:title, 'Events') %>
<h1>Events</h1>

<div class="container">
  <div class="row">
    <%= will_paginate class: 'center', inner_window: 2, outer_window: 0 %>
    
    <%= render @events %>

    <%= will_paginate class: 'center', inner_window: 2, outer_window: 0 %>
  </div>
</div>

app/views/events/new.html.erb
<% provide(:title, "New event") %>
<h1>New event</h1>

<div class="container">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@event) do |f| %>
      <%= render 'error_messages' %>

      <%= f.label :name, "Title" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :location %>
      <%= f.text_field :location, class: 'form-control' %>

      <%= f.label :start, "Start time"%>
      <div class="form-group">
        <div class="input-group date">
          <%= f.text_field :start, class: 'form-control', id: 'datetimepicker'%>
          <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
          </span>
        </div>
      </div>

      <%= f.label :end, "End time"%>
      <div class="form-group">
        <div class="input-group date">
          <%= f.text_field :end, class: 'form-control', id: 'datetimepicker2'%>
          <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
          </span>
        </div>
      </div>

      <%= f.label :link %>
      <%= f.text_field :link, class: 'form-control' %>

      <%= f.submit "Create event", class: 'btn btn-danger' %>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<% provide(:title, 'Event') %>

<div class="container-fluid">
  <div class="col-md-4">
    <div class="center">
      <% if @event.users.include?(current_user) %>
        <%= link_to "Not going", delete_user_from_event_path(@event),
                    class: 'btn btn-danger', method: :patch %>
        <%= link_to "Going", assign_user_to_event_path(@event),
                    class: 'btn btn-danger disabled', method: :patch %>
      <% else %>
        <%= link_to "Not going", delete_user_from_event_path(@event),
                    class: 'btn btn-danger disabled', method: :patch %>
        <%= link_to "Going", assign_user_to_event_path(@event),
                    class: 'btn btn-danger', method: :patch %>
      <% end %>
    </div>

    <%= form_for(@event, url: edit_event_path(@event), html: { method: 'GET' }) do |f| %>

      <%= f.label :name, "Title" %>
      <%= f.text_field :name, class: 'form-control', readonly: true %>

      <%= f.label :location %>
      <%= f.text_field :location, class: 'form-control', readonly: true %>

      <%= f.label :start, "Start time"%>
      <%= f.text_field :start, class: 'form-control', readonly: true %>

      <%= f.label :end, "End time"%>
      <%= f.text_field :end, class: 'form-control', readonly: true %>


      <%= f.label :link %>
      <a href="<%= @event.link %>">
        <%= f.text_field :link, class: 'form-control', readonly: true %>
      </a>

      <% if current_user.admin? %>
        <%= f.submit "Edit event", class: 'btn btn-danger' %>
      <% end %>
    <% end %>
  </div>

  <div class="col-md-8">
    <h1>List of participants(<%= @users.count %>):</h1>
    <%= will_paginate @users, class: 'center', inner_window: 2, outer_window: 0 %>

    <%= render 'users' %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <small>
    The <a href="http://www.husariaraceteam.pl/">Husaria Race Team Site</a>
    by Karol Bielecki
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top my-navbar" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbarCollapse">
        <i class="glyphicon glyphicon-menu-hamburger" style="color:#fff"></i>
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("husaria-logo.png", alt: "Husaria logo"),
                  root_path %>
    </div>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "My profile", user_path(current_user) %></li>
          <% if current_user.admin? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="" id="navbarDropdownMenuLink1"
                 data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Events
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink1">
                <li><%= link_to "Show", events_path, class: 'dropdown-item' %></li>
                <li><%= link_to "Add new", new_event_path, class: 'dropdown-item' %></li>
              </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="" id="navbarDropdownMenuLink2"
                 data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Members
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink2">
                <li><%= link_to "Show", users_path, class: 'dropdown-item' %></li>
                <li><%= link_to "Add new", signup_path, class: 'dropdown-item' %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Events", events_path %></li>
            <li><%= link_to "Members", users_path, class: 'dropdown-item' %></li>
          <% end %>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sklep", 'http://husarz.pl/' %></li>
          <li><%= link_to "Log In", login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container-fluid">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>

      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>

    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/users/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_events.html.erb
<% @events.each do |event| %>
  <div class="col-sm-6 col-md-6">
    <a href="<%= event_path(event) %>" class="event-jumbotron">
      <div class="jumbotron event-jumbotron">
        <p><%= event.name %></p>
      </div>
    </a>
  </div>
<% end %>

app/views/users/_user.html.erb
<tr>
  <td><%= link_to global_counter_add, user, class: 'btn btn-name' %></td>
  <td><%= link_to (user.surname + " " + user.name), user, class: 'btn btn-name' %></td>
  <td>
    <% if current_user.admin? && !user.admin? %>
      <%= link_to user, method: :delete,
                        data: { confirm: "Are you sure?" },
                        class: 'btn btn-delete' do %>
        <span class="glyphicon glyphicon-trash"></span>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/users/edit.html.erb
<% provide(:title, 'Profile') %>
<h1>Profile</h1>

<div class="container">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', readonly: true unless current_user.admin? %>
      <%= f.text_field :name, class: 'form-control' if current_user.admin? %>

      <%= f.label :surname %>
      <%= f.text_field :surname, class: 'form-control', readonly: true unless current_user.admin? %>
      <%= f.text_field :surname, class: 'form-control' if current_user.admin? %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :sex %>
      <%= f.select :sex, [['Male', 'Male'], ['Female', 'Female']], {}, class: 'form-control' %>

      <%= f.label :password, "New password" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Edit", class: 'btn btn-danger' %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Members') %>

<% if current_user.admin? %>
  <div class="container-fluid">
<% else %>
  <div class="container">
<% end %>
  <div class="col-md-6 col-md-offset-3">
    <%= will_paginate class: 'center', inner_window: 2, outer_window: 0 %>

    <table class="table users">
      <tbody>
          <% global_counter_assign(params[:page].to_i * 20 - 20) %>
          <%= render @users %>
      </tbody>
    </table>

    <%= will_paginate class: 'center', inner_window: 2, outer_window: 0 %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Create new user') %>
<h1>Create new user</h1>

<div class="container">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :surname %>
      <%= f.text_field :surname, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :sex %>
      <%= f.select :sex, [['Male', 'Male'], ['Female', 'Female']], {}, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create new user", class: 'btn btn-danger' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, 'Profile') %>

<div class="container-fluid">
  <div class="col-md-4">
    <%= form_for(@user, url: edit_user_path(@user), html: { method: 'GET' }) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', readonly: true %>

      <%= f.label :surname %>
      <%= f.text_field :surname, class: 'form-control', readonly: true %>

      <% if current_user?(@user) %>
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control', readonly: true %>

        <%= f.label :sex %>
        <%= f.text_field :sex, class: 'form-control', readonly: true %>

        <%= f.submit "Edit user", class: 'btn btn-danger' %>
      <% end %>
    <% end %>
  </div>

  <div class="col-md-8">
    <h1>List of attending events(<%= @events.count %>):</h1>
    <%= will_paginate @events, class: 'center', inner_window: 2, outer_window: 0 %>

    <%= render 'events' %>
  </div>
</div>